"""test_tech_writer.py — RED stubs for Phase 5 tech-writer step (Wave 0).

All tests skip until corresponding Wave 1 module is created.
"""
from __future__ import annotations

import importlib
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def gd():
    """Lazy import of scripts/gsd_driver.py — skips when not yet available."""
    try:
        return importlib.import_module("gsd_driver")
    except ImportError:
        pytest.skip("gsd_driver module not yet available (Wave 1 target)")


# ---------- ROLE-07: tech-writer step emits /gsd-docs-update ----------

def test_tech_writer_step_emits_gsd_docs_update(gd, tmp_project_root, writer, capsys):
    """ROLE-07: emit_next_command at phase_step=9 prints '/gsd-docs-update' to stdout.

    Behavior test — does NOT check PHASE_STEP_COMMANDS dict key. Key 9 is removed
    from PHASE_STEP_COMMANDS in Plan 05-05 (replaced by an in-line handler that
    invokes the tech-writer + humanizer pipeline). Wave 1 must assert on
    emit_next_command output, never on `gd.PHASE_STEP_COMMANDS[9]` directly.
    """
    pytest.skip("Wave 1 target")


def test_phase_step_commands_includes_tech_writer(gd, tmp_project_root, writer, capsys):
    """ROLE-07: emit_next_command stdout at phase_step=9 contains '/gsd-docs-update'.

    NOTE: key 9 is removed from PHASE_STEP_COMMANDS in Plan 05-05; this test checks
    emit_next_command output behavior, NOT direct dict key access.
    """
    pytest.skip("Wave 1 target")


# ---------- ROLE-07: phase advance shifted to step 10 ----------

def test_phase_step_10_advances_phase(gd, tmp_project_root, writer):
    """ROLE-07: emit_next_command at phase_step=10 increments current_phase and resets phase_step."""
    pytest.skip("Wave 1 target")


# ---------- ROLE-07: humanizer_score state field ----------

def test_humanizer_score_field_allowed(writer, tmp_project_root):
    """ROLE-07: state_writer.py accepts writes for the 'humanizer_score' field."""
    pytest.skip("Wave 1 target")


def test_humanizer_missing_fallback(gd, tmp_project_root, writer, monkeypatch):
    """ROLE-07: when humanizer SKILL.md is missing, tech-writer step writes
    humanizer_score='skipped' to state.md and continues without crashing."""
    pytest.skip("Wave 1 target")


# ---------- ROLE-07: README dev-team section ----------

def test_readme_has_dev_team_section(tmp_project_root):
    """ROLE-07: README.md generated by tech-writer step contains '## How OSBuilder built this'
    and all 8 role names (PM, Architect, Frontend, Backend, DevOps, QA, Reviewer, Tech Writer).
    """
    pytest.skip("Wave 1 target")
